### ISSUE TITLE
maketest failure

### ISSUE THREAD

**Issue by denisnichita** [jmmccracken/PAI#1] opened 2018-09-17 10:08 UTC
The maketest fails. The diff finds differences between the .dat and .test files.

**Comment by norbertgerena** [comment] 2022-11-29 09:14
> The maketest fails. The diff finds differences between the .dat and .test files.

Hi I found the bug in the dXZShadow calculation. The original code will give you an embedding that looks like this [Xt, Xt-1, Xt-3,  0, 0, 0] for E=3 and Ey=3. I tried to fixed it but it still won't pass testPAI. Here's the link to my forked repo: 
https://github.com/norbertgerena/PAI.git.

**Comment by rweigel** [comment] 2022-12-18 22:17
I've emailed James, who wrote all of the code for this. He should be able to comment on the pull request.

The fact that the test fails is unexpected. I'm sure it was passing at the time of the last commit.

Would you post your diff? I get

```
diff check/PAItestingAB3_out_PAI3.dat check/PAItestingAB3_out_PAI3.test
1c1
< 0.99999939455157760282,0.99999895588861131834,0.99564446721245947192,0.99176730309305505262
---
> 0.99999939455157760282,0.99999939455157760282,0.99564446721245947192,0.99564446721245947192
```
Using

```
g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by jmmccracken** [comment] 2022-12-19 12:39
It looks like I'm seeing the same make test failure. The PAI output file seems to differ from the test file, exactly as Bob posted. Unfortunately, this codebase is 8 years old and has not been maintained. I'm not sure I still have the code used to generate the test data files. If you're interested in using CCM/PAI, then I would strongly encourage you to implement this algorithm in Python from scratch. Trying to wrap this old C++ library in Python bindings is probably more trouble than it's worth. I think there are much more modern libraries like numba or jax that would make building the shadow manifold much more efficient. If you're looking for other examples of using CCM/PAI, then I'd suggest looking through the examples on the ECA repo (https://github.com/jmmccracken/ECA). I'll see if I can dig up the test generation code.

**Comment by norbertgerena** [comment] 2022-12-19 13:46
Hi @jmmccracken and  @rweigel. Thank you. I've already implemented PAI using Python (see https://github.com/PrinceJavier/causal_ccm). However, due to the uncertainty in the shadow manifold, I made the shadow manifold embedding general. 

The embedding, $(X_t, X_{t-1}, ..., Y_t)$ to estimate $X_t$, described in the paper, does not reproduce figures 6b and 6d.
![image](https://user-images.githubusercontent.com/111188631/208437706-a26393ae-2f58-4754-9b9f-5f3a5ad676de.png).

However, I found the embedding, $(X_{t-1}, X_{t-2},..., Y_t)$ to estimate $X_t$ seems to work (will produce conclusions consistent with our intuition of "driving"), but will still not result in the figures above.

Please let me know if my understanding of the shadow manifold embedding used to create figure 6 is wrong.

In the meantime, I'll look at the ECA repo.

**Comment by jmmccracken** [comment] 2022-12-20 19:23
Hi @norbertgerena. I'm glad to hear you're getting some of these state space methods into Python. I think there's already a Julia and R package, but I know Python is much more popular with data scientists. If you're working in Python, then you can generate the input time series for Fig. 6 as follows:
```
def eqn2(x0, y0, rx, ry, Bxy, Byx, L):
    x = [x0]
    y = [y0]
    for idx in np.arange(1, L):
        x.append(x[idx-1]*(rx-rx*x[idx-1]-Bxy*y[idx-1]))
        y.append(y[idx-1]*(ry-ry*y[idx-1]-Byx*x[idx-1]))
    return(x, y)
x,y = eqn2(0.2, 0.4, 3.7, 3.7, 0, 0.32, 1000)
`````
These generating equations are often referred to as a "coupled logistic map" (see, e.g., [this Wikipedia article](https://en.wikipedia.org/wiki/Coupled_map_lattice)).  They are popular in non-linear time series analysis because they are _very_ sensitive to the initial values and parameters. We tried to be specific in the paper, but even using slightly different values can lead to vastly different shadow manifolds. I talk about this a little in the ECA work. 

Once you build the time series, they need to be formatted in a specific way for this old PAI code to read them; i.e.,
```
with open('eqn2.dat', 'w') as f:
    for idy,x_elem in enumerate(x):
        y_elem = y[idy]
        dat_line = f'{x_elem},{y_elem};\n'
        f.write(dat_line)
```
Once the input file is written, you can call the PAI executable with
```
./PAI -E 3 -t 1 -L 1000 -n 1 -Ey 3 -ty 1 -f eqn2.dat -o eqn2_pai.out -eY eqn2_pai_eY.out -PAI -v
```
which should generate the output file "eqn2_pai_eY.out" that contains the estimated series you want to plot to reproduce Figure 6. Unfortunately, the output file format is just an ordered list of the time series points. So, you'll need to take care when reading the data back into Python and make sure you cut up the series into "X given X", "X given XY", "Y given Y", and "Y given YX" correctly. Remember that the estimated series are shorter than the original series by the embedding dimension. The output format is shown in STDOUT as part of the PAI help: `PAI -h`.

Here's a quick reproduction of Fig. 6b using exactly the procedure I just described and a fresh pull of this repo:
![Fig6b_quick_redo](https://user-images.githubusercontent.com/7997883/208747121-8b404c39-ebc7-426e-8b68-d9514ad2fec6.png)
and here's Fig. 6d:
![Fig6d_quick_redo](https://user-images.githubusercontent.com/7997883/208747185-35d21e69-684a-44b4-b98f-f8982f18bf1f.png)
As I sit here and look at these, it does seem like there are some slight differences between these plots and the published ones. In fact, these plots seem to show a stronger correlation than what we published. But, I was much more careful in generating the published plots. Everything you see here is just the good old matplotlib defaults. I actually think I generated the original publication plots in Matlab, not Python. But, I'm still trying to scrounge up that old code.

I hope this helps in the meantime. Also, I'm not sure what you're trying to do with CCM/PAI, but I think it's important to remember that there's nothing special about the "shadow" embedding when generating these estimated series. There's lots of possible embeddings (as long as they obey [Taken's theorem](https://en.wikipedia.org/wiki/Takens%27s_theorem)). This codebase cannot support anything other than the shadow-manifold-type embedding used in CCM, but maybe your new Python package can support general diffeomorphisms for even better forecasting and/or exploratory causal analysis.

**Comment by norbertgerena** [comment] 2022-12-21 01:23
Hi @jmmccracken. Thank you for the detailed discussion.

I've encountered the JuliaDynamics package. In fact, I have been communicating with its authors as well regarding an issue I found, related also to the embedding. They even asked me to be a contributor, which is really exciting.

I actually used the same function and parameters when I was trying to replicate figures 6b and 6d.

I'm not sure if you have seen my pull request (https://github.com/jmmccracken/PAI/pull/2). I think one of the reason why we can't replicate figures 6b and 6d (and why the make test won't pass) using this library is because of the delay vectors that are being created.  Here's a snapshot of the last few delay vectors (for $Y|YX$, using the PAI params you used above):

![image](https://user-images.githubusercontent.com/111188631/208796362-40941ef2-65fc-4423-b985-8bce1eb5fb53.png)

Instead of generating $(Y_t, Y_{t-1}, Y_{t-2}, X_t, X_{t-1}, X_{t-2})$, the code produced $(Y_t, Y_{t-1}, Y_{t-2}, 0, 0, 0)$.

Note: I just printed the delay vectors by crudely adding these print statements:
![image](https://user-images.githubusercontent.com/111188631/208798109-2b115912-0f90-4967-b02e-a8cd085894af.png)

**Comment by jmmccracken** [comment] 2022-12-21 20:19
So, there's a few things happening here. First, there is a bug in the code, exactly as you say. Thank you for finding it, and I apologize to @denisnichita for not responding when this issue was originally raised. It seems the second time series was never being added to the shadow manifold, which is why you were seeing those zeros. I looked at your proposed fix, and I don't think it works in the general case when the shadow is built from differently sized embeddings of X and Y. I _think_ my fix will work, but please let me know if there's still a bug.

Second, I went back and looked at the old work we did when writing those papers. All of those computations were done with MATLAB code and a few C routines. Apparently this codebase was created later and meant to be a more computationally efficient version of that old code (which is why this code focuses on threading the shadow manifold creation). Unfortunately, there's quite a few test files sitting around, and I think it may be impossible to know exactly what embedding and time lag parameters were used to generate the make test files in this repo. There is no real documentation for how those files were generated or what exactly these make tests were meant to test. I'm not even 100% sure I know the generating equations, but that's less of an issue because the time series data file is checked in to this repo. I ran the equation series from the PAI paper using the process we described above (and the bug-fixed code) and all the values seem to agree with the published results. So, I went ahead and updated the make test data file to match what I assume was intended to be the original test output.

I'm also going to update the README to link to your repo and the Julia one. This codebase should be considered a research resource, not a production-quality codebase. Looking at this code after a decade away makes it clear to me that it's fragile, does little-to-no error checking, and is not user-friendly. There are edge cases that I would expect someone might want to explore (e.g., embedding non-concurrent histories into the shadow) that this codebase does not support. I really appreciate your help with all of this. I'm going to close this comment, but feel free to email me if you've got more questions (or open more issues if I didn't actually fix the bugs).

**Closed as completed by jmmccracken** 2022-12-21 20:19 UTC

**Comment by norbertgerena** [comment] 2022-12-22 01:49
Thank you so much @jmmccracken and @rweigel!
